# Generated by Django 4.1.7 on 2023-02-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
