# Generated by Django 4.1.7 on 2023-02-28 19:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_category_rename_content_note_text_note_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="reminder",
            field=models.DateTimeField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date.today)
                ],
            ),
        ),
    ]
