# Generated by Django 4.1.7 on 2023-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_note_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
